# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b95c0b47329e3a35017b1f9d191026fda085af854db19d38368debb40626adc970bfeca8591fbe2aa950f601f7f1a0186bfd118d74fe185f7f02a93fc790f7f

test:
  secret_key_base: 676ed60f7ed754fdd46ac73027ccca635c685132a8b1e0ea3b6422de238a2849aa0e09ade0330e2f7b2d5a8ce683bd6edc6bac778c1650f8b6d4e1c3f178776c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
